'use strict';

module.exports = {
  SIGNUP_FAILED: 'SIGNUP_FAILED',
  SIGNUP_FIELD_ITEM_UPDATED: 'SIGNUP_FIELD_ITEM_UPDATED',
  SIGNUP_COMPONENT_UNMOUNTED: 'SIGNUP_COMPONENT_UNMOUNTED',
  SIGNUP_UNITENTIFIED_ERROR: 'SIGNUP_UNITENTIFIED_ERROR',
  SIGNUP_CLEAR_UNIDENTIFIED_ERROR: 'SIGNUP_CLEAR_UNIDENTIFIED_ERROR',  

  LOGIN_FIELD_ITEM_UPDATED: 'LOGIN_FIELD_ITEM_UPDATED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_COMPONENT_UNMOUNTED: 'LOGIN_COMPONENT_UNMOUNTED',
  LOGIN_UNITENTIFIED_ERROR: 'LOGIN_UNITENTIFIED_ERROR',
  LOGIN_CLEAR_UNIDENTIFIED_ERROR: 'LOGIN_CLEAR_UNIDENTIFIED_ERROR',
  LOGIN_SUCESS_BROADCAST: 'LOGIN_SUCESS_BROADCAST',

  HEADER_COMPONENT_UNMOUNTED: 'HEADER_COMPONENT_UNMOUNTED',
  HEADER_LOGIN_RESPONSE_LOADED: 'HEADER_LOGIN_RESPONSE_LOADED',
  HEADER_UNITENTIFIED_ERROR: 'HEADER_UNITENTIFIED_ERROR',

  EMERGENCIES_UNITENTIFIED_ERROR: 'EMERGENCIES_UNITENTIFIED_ERROR',
  EMERGENCIES_DATA_LOADED: 'EMERGENCIES_DATA_LOADED',
  EMERGENCIES_COMPONENT_UNMOUNTED: 'EMERGENCIES_COMPONENT_UNMOUNTED',
  EMERGENCIES_MAP_LOADED: 'EMERGENCIES_MAP_LOADED',

  EMERGENCY_DIALOG_CLOSE: 'EMERGENCY_DIALOG_CLOSE',
  EMERGENCY_MARK_AS_RECEIEVED: 'EMERGENCY_MARK_AS_RECEIEVED',
  EMERGENCY_DIALOG_COMPONENT_UNMOUNTED: 'EMERGENCY_DIALOG_COMPONENT_UNMOUNTED',
  EMERGENCY_DIALOG_DATA_LOADED: 'EMERGENCY_DIALOG_DATA_LOADED',
  EMERGENCY_DIALOG_DATA_RECEIVED: 'EMERGENCY_DIALOG_DATA_RECEIVED',
  EMERGENCY_MAP_LOADED: 'EMERGENCY_MAP_LOADED',

  REPORTS_COMPONENT_UNMOUNTED: 'REPORTS_COMPONENT_UNMOUNTED',
  REPORTS_DATA_LOADED: 'REPORTS_DATA_LOADED',
  REPORTS_UNITENTIFIED_ERROR: 'REPORTS_UNITENTIFIED_ERROR',

  REPORT_DIALOG_COMPONENT_UNMOUNTED: 'REPORT_DIALOG_COMPONENT_UNMOUNTED',
  REPORT_DIALOG_CLOSE: 'REPORT_DIALOG_CLOSE',
  REPORT_DIALOG_UNITENTIFIED_ERROR: 'REPORT_DIALOG_UNITENTIFIED_ERROR',
  REPORT_UPDATE_MESSAGE: 'REPORT_UPDATE_MESSAGE',
  REPORT_SEND_MESSAGE_SUCCESS: 'REPORT_SEND_MESSAGE_SUCCESS',
  REPORT_SEND_MESSAGE_FAILED: 'REPORT_SEND_MESSAGE_FAILED',
  REPORT_SEND_UNITENTIFIED_ERROR: 'REPORT_SEND_UNITENTIFIED_ERROR',
  REPORTS_MESSAGES_DATA_LOADED: 'REPORTS_MESSAGES_DATA_LOADED',
  REPORT_FOLLOWUP_INITIATED: 'REPORT_FOLLOWUP_INITIATED',
  REPORT_DIALOG_INIT_DATA: 'REPORT_DIALOG_INIT_DATA'

};
