'use strict';

module.exports = {
  LOGIN_FIELD_ITEM_UPDATED: 'LOGIN_FIELD_ITEM_UPDATED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_COMPONENT_UNMOUNTED: 'LOGIN_COMPONENT_UNMOUNTED',
  LOGIN_UNITENTIFIED_ERROR: 'LOGIN_UNITENTIFIED_ERROR',
  LOGIN_CLEAR_UNIDENTIFIED_ERROR: 'LOGIN_CLEAR_UNIDENTIFIED_ERROR',
  LOGIN_SUCESS_BROADCAST: 'LOGIN_SUCESS_BROADCAST',

  HEADER_COMPONENT_UNMOUNTED: 'HEADER_COMPONENT_UNMOUNTED',
  HEADER_LOGIN_RESPONSE_LOADED: 'HEADER_LOGIN_RESPONSE_LOADED',
  HEADER_UNITENTIFIED_ERROR: 'HEADER_UNITENTIFIED_ERROR',

  LANDING_EMERGENCIES_LOADED: 'LANDING_EMERGENCIES_LOADED',
  LANDING_REPORTS_LOADED: 'LANDING_REPORTS_LOADED',
  LANDING_UNITENTIFIED_ERROR: 'LANDING_UNITENTIFIED_ERROR',
  LANDING_COMPONENT_UNMOUNTED: 'LANDING_COMPONENT_UNMOUNTED'
};
